### ISSUE TITLE
H 19.5 error

### ISSUE THREAD

**Issue by faddysaeed** [paulwinex/pw_Houdini_VEX_Editor#11]
There is an error in the VEX Editor script.

Traceback (most recent call last):
     File "", line 1, in
     File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.435/houdini/python_panels/vexeditor.pypanel", line 7, in createInterface
     in a single file. -->
     File "C:\Program Files\Side Effects Software\Houdini 19.5.435\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
     return original_import(name, *args, **kwargs)
     File "C:\Users/FADDY/Documents/houdini19.5/scripts/python\pw_VEX_Editor\__init__.py", line 1, in
     import editor_panel
     File "C:\Program Files\Side Effects Software\Houdini 19.5.435\python39\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
     return original_import(name, *args, **kwargs)
    ModuleNotFoundError: No module named 'editor_panel'

**Comment by paulwinex** [comment]
Sorry, this hasn't been updated for a long time. I was going to redo the project from scratch but haven't gotten around to it yet.
Any way, the error looks like an incorrect installation.

**Comment by faddysaeed** [comment]
i installed the pw_VEX_Editor folder and  hqt.py file into this folder
C:\Users\FADDY\Documents\houdini19.5\scripts\python

I followed the installation video. but still same problem
thank you for your time
