### ISSUE TITLE
error starting script

### ISSUE THREAD

**Issue by ghost** [paulwinex/pw_Houdini_VEX_Editor#3]
I get the following in the Houdini Pane Tab;

**There is an error in the VEX Editor script.

Traceback (most recent call last):
     File "", line 1, in 
     File "", line 9, in createInterface
     File "C:/Users/admin/Documents/houdini16.0/scripts/python\pw_VEX_Editor\__init__.py", line 1, in 
     import editor_panel
     File "C:/Users/admin/Documents/houdini16.0/scripts/python\pw_VEX_Editor\editor_panel.py", line 9, in 
     import hou, hqt
    SyntaxError: ('invalid syntax', ('C:/Users/admin/Documents/houdini16.0/scripts/python\\pw_VEX_Editor\\hqt.py', 7, 1, '\n'))**

Runing latest Houdini version 16.0.504.20

**Comment by paulwinex** [comment]
Hi.
Try to replace hqt.py with new version. Maybe its encode error
https://github.com/paulwinex/hqt

2017-04-14 15:57 GMT+03:00 whitezeroblack <notifications@github.com>:
