### ISSUE TITLE
Houdini 16.5.323 error at start

### ISSUE THREAD

**Issue by doppioslash** [paulwinex/pw_Houdini_VEX_Editor#6]
Windows 10
Houdini Indie 16.5.323
Version: master, commit cf7b1f6b969ff0c5288f33c8b598e49b6f0c97b6

After installing according to instructions, and opening the panel, the panel shows this error:

```
There is an error in the VEX Editor script.

Traceback (most recent call last):
     File "", line 1, in 
     File "", line 9, in createInterface
     File "C:/Users/claud/OneDrive/Documents/houdini16.5/scripts/python\pw_VEX_Editor\__init__.py", line 1, in 
     import editor_panel
     File "C:/Users/claud/OneDrive/Documents/houdini16.5/scripts/python\pw_VEX_Editor\editor_panel.py", line 9, in 
     import hou, hqt
    ImportError: No module named hqt
```

**Comment by doppioslash** [comment]
Nevermind, missed a bit in the install video.

**Comment by paulwinex** [comment]
hqt should be installed manually.
